jobs:
- job: Windows
  pool:
    name: zempot-agent-linux
    vmImage: ubuntu-20.04
  steps:
  - script: echo hello from Windows
- job: Linux
  pool:
    name: zempot-agent-linux
    vmImage: ubuntu-18.04
  steps:
  - script: echo hello from Linux