# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: zempot-agent-linux
  vmImage: ubuntu-18.04

steps:
- script:
    echo 'jwy test'
  displayName: 'Check prerequizie'

- task: CmdLine@2
  inputs:
    script: |
      echo converting file encoding
      find ./ -type f -iname *.h -exec sh -c 'iconv -f $(file -bi "$1" | sed -e "s/.*[ ]charset=//") -t utf-8 -o converted "$1" && mv converted "$1"' -- {} \;
      echo converting file encoding is end
    workingDirectory: './'

#- script: |
#    sudo apt-get update
#    sudo apt-get -qq list libjsoncpp-dev 2>/dev/null | grep -qE "(installed|upgradeable)" || sudo apt-get install -y libjsoncpp-dev
#    sudo apt-get -qq list libcurl4-openssl-dev 2>/dev/null | grep -qE "(installed|upgradeable)" || sudo apt-get install -y libcurl4-openssl-dev
#  displayName: 'Run a multi-line script(JWY)'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
