# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: 
    apt-get update
    apt -qq list libcurl4-openssl-dev 2>/dev/null | grep -qE "(installed|upgradeable)" || apt-get install libcur4-openssl-dev
    apt-get install -y libjsoncpp-dev

  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
